### ISSUE TITLE
10.14 UX430UA

### ISSUE THREAD

**Issue by gulios** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#1]
Hi, can you prepare kext with 10.14 compatibility ?
You wrote that https://github.com/hieplpvip/VoodooI2C/tree/native so i just want to test it.

It works with changes https://github.com/alexandred/VoodooI2C/issues/70

Thank you !

**Comment by gulios** [comment]
but it's not compatible with 10.14, right ? I moved to Mojave.

**Comment by hieplpvip** [comment]
Do you use Gitter? GitHub reports error when I try to upload the kexts.

**Comment by gulios** [comment]
no, i don't use it.
Maybe just upload it here https://www.tonymacx86.com/threads/asus-ux430ua-kaby-lake-i7-7500u-intel-hd-graphics-620.225847/

**Comment by hieplpvip** [comment]
I would prefer not to upload this publicly. A private chat is better.
Signing up Gitter is pretty easy, you can find me on Gitter: @hieplpvip
I have another kext that you may want to test too

**Comment by gulios** [comment]
ok, i'm in
