### ISSUE TITLE
Keyboard stop working after Mojave update

### ISSUE THREAD

**Issue by mynameisvasco** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#10]
**What is your laptop?**
Ux430ua
**Which version of macOS are you using?**
10.14 final release
**Describe the problems**
I updated this repository to lastest version and after update macos from Mojave beta to Mojave final keyboard stops working

**Comment by hieplpvip** [comment]
Please send output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)

**Comment by AwlsomeAlex** [comment]
I would try again, there was a few problems experienced with VoodooPS2Controller.kext

**Comment by hieplpvip** [comment]
@mynameisvasco This repo supports Mojave now, please try again
