### ISSUE TITLE
Audio UX330 Mojave

### ISSUE THREAD

**Issue by oesayan** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#12]
UX330

Mojave

Everything works perfectly, except for audio. There are no audio inputs or outputs in the settings.

Attached output from gendebug, just in case.

[debug_31814.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2427370/debug_31814.zip)

**Additional context**
Actually I broke my High Sierra install, did a clean Mojave install, and it worked, without any kexts besides FakeSMC. Even the graphics in native resolution with all the memory. That was weird, so I installed your build, everything works amazing except for the sound 🤕 
Thank you!

**Comment by hieplpvip** [comment]
There are two UX330: KabyLake and KabyLake-R. Are you sure you chose the right one?

To be sure, can you send me your AIDA64 report?

**Comment by amsalud** [comment]
@oesayan You can try Voodoohda 
https://github.com/chris1111/VoodooHDA-2.9.0-Clover-V12/files/2087523/VoodooHDA.2.9.0.Clover-V12.zip

**Comment by hieplpvip** [comment]
@aaronsalud VoodooHDA is not the optimal solution. HDMI audio doesn't work with it

**Comment by oesayan** [comment]
Sorry for late answer, here is the AIDA64 report on CPU, video and audio.


```
Motherboard:
      CPU Type                                          DualCore Intel Core i5-7200U, 3100 MHz (31 x 100)
      Motherboard Name                                  Asus ZenBook UX330UAK
      Motherboard Chipset                               Intel Sunrise Point-LP, Intel Kaby Lake-U
      System Memory                                     [ TRIAL VERSION ]
      BIOS Type                                         AMI (05/02/2017)
    Display:
      Video Adapter                                     Intel(R) HD Graphics 620  (1 GB)
      Video Adapter                                     Intel(R) HD Graphics 620  (1 GB)
      Video Adapter                                     Intel(R) HD Graphics 620  (1 GB)
      3D Accelerator                                    Intel HD Graphics 620
      Monitor                                           Универсальный монитор PnP [NoDB]

    Multimedia:
      Audio Adapter                                     Intel Kaby Lake HDMI @ Intel Sunrise Point-LP PCH - High Definition Audio Controller [C1]
      Audio Adapter                                     Realtek ALC255 @ Intel Sunrise Point-LP PCH - High Definition Audio Controller [C1]
```

**Comment by hieplpvip** [comment]
There are several layout-id for ALC255 available in AppleALC: 3, 13, 17, 18, 27, 28, 99. You need to try them all to know which works best

To change layout-id, open SSDT-UX330-KABY.aml, find method HDEF._DSM and replace current layout-id with the above ones. Tell me which works best

**Comment by amsalud** [comment]
@oesayan Try layout id 3. Works for me

**Comment by hieplpvip** [comment]
@aaronsalud Did you test everything (speaker, headphone, internal mic, external mic)?

**Comment by amsalud** [comment]
@hieplpvip Yes I can confirm that
