### ISSUE TITLE
Problems with UX330CA

### ISSUE THREAD

**Issue by morpheus65535** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#13]
**What is your laptop?**
Asus Zenbook UX330CA

**Which version of macOS are you using?**
10.13.6

**Describe the problems**
- Touchpad stop functioning sometime.
- Keyboard backlight doesn't work (FN-F3 or F4 OSD work but no change).
- ~~Audio card not detected.~~
- Video blink sometime.

**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**
[debug_11541.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2430107/debug_11541.zip)

**Screenshots**
n/a

**Additional context**
Installed 2 days ago with latest github code. Thanks for this script, it's a valuable help for a noobs.

**Comment by morpheus65535** [comment]
Audio fixed with: https://github.com/chris1111/VoodooHDA-2.9.0-Clover-V12/files/2087523/VoodooHDA.2.9.0.Clover-V12.zip

**Comment by hieplpvip** [comment]
VoodooHDA is not optimal solution

**Comment by morpheus65535** [comment]
> VoodooHDA is not optimal solution

Yeah I know but at least I got something. I don't use HDMI audio so for now this one is fixed. If you want me to test something, it will be a pleasure!

**Comment by hieplpvip** [comment]
Give me your SMC dump

**Comment by morpheus65535** [comment]
Noobs question: how do I do that? :-)

**Comment by hieplpvip** [comment]
Will show you when I get home.

What is your audio card?

**Comment by hieplpvip** [comment]
Run `./smc -l`
[smc.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2430385/smc.zip)

**Comment by hieplpvip** [comment]
There are several things I need you to do:
- Download DEBUG version of AsusSMC, copy it to `CLOVER/kexts/Other`
- Run `./uninstall_kexts.sh`
- Add boot argument `-asussmcdbg` to `config.plist`, reboot.
- Open Console, find `ambient` and `AsusSMC`, tell me what you found

Also, if possible, can you upload full report from AIDA64 on Windows?

**Comment by hieplpvip** [comment]
Have you updated to latest BIOS?

**Comment by morpheus65535** [comment]
Thanks for your help but unfortunately, this is way too unstable. It's my work laptop and I can keep it that way. I have to go back to Windows for now. Maybe I'll try again during vacation when I'll have more time to debug.

**Comment by hieplpvip** [comment]
You can install both macOS and Windows. macOS is running well on my laptop. It may take time but the result is worth it

**Comment by morpheus65535** [comment]
Yes I know I would really like this to work but I have to postpone it for now. Thanks for your time!
