### ISSUE TITLE
Enable Touchpad for Asus S410UA 

### ISSUE THREAD

**Issue by saiftheboss7** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#14]
First of all sorry that I'm creating this as a issue. I appreciate your work whole heartedly. Seems I am stuck and that's why wanted to have some help (if you can) 

What is your laptop?
Asus Vivobook S410UA

Which version of macOS are you using?
10.14

Describe the Problem 
I can't seem to enable basic Touchpad support. Currently I am using Rehabman's latest VoodooPS2 controller kext and your two i2c kext. I didn't add anything in dsdt or in clover's config.plist. I am kind of new to Hackintosh era. Any idea how can I add basic Touchpad support? My laptop has Elan1300 (I found it from Windows > Device Manager). 

Thanks in advance.

**Comment by hieplpvip** [comment]
See GPIO pinning instruction at voodooi2c.github.io
