### ISSUE TITLE
Why Don't use SMCHelper-64 ? 

### ISSUE THREAD

**Issue by theagilecoder** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#15]
WHy have you mentioned Don't use SMCHelper-64 in the installation instructions ? SHould I heed this for my Asus Zenbook UX360CA Skylake ?

**Comment by hieplpvip** [comment]
This repo doesn't use FakeSMC, instead it uses VirtualSMC which doesn't work with SMCHelper.

Moreover, UX360 is not supported
