### ISSUE TITLE
make_acpi.sh error

### ISSUE THREAD

**Issue by asmyshlyaev177** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#16]
**What is your laptop?**
Asus UX310U
**Which version of macOS are you using?**
I use ubuntu 18  (64 bit)
**Describe the problems**
I try to run make_acpi.sh but get error 

> ./make_acpi.sh: line 9: ./tools/iasl: cannot execute binary file: Exec format error
> ./make_acpi.sh: line 10: ./tools/iasl: cannot execute binary file: Exec format error

**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**

**Screenshots**

**Additional context**

**Comment by hieplpvip** [comment]
This repo can only be runned on macOS. Closed
