### ISSUE TITLE
Commit 41b7493 - Random Screen Flashing (UX330UAR)

### ISSUE THREAD

**Issue by AwlsomeAlex** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#17]
ASUS ZenBook UX330UAR (8th Generation)

macOS 10.14 Mojave

On random occasions, the display will go black and suddenly turn back to normal as quickly as it goes black. Noticed it about 3 times so far in the last hour, might this option being disabled have something to do with it or something with WhateverGreen?

Will provide gen_debug if needed.

Can't screenshot (Too quick to catch)

**Comment by AwlsomeAlex** [comment]
Also Microphone doesn't work.

**Comment by AwlsomeAlex** [comment]
Alright, my GPU (Screen?) decided to have a panic attack (The Graphics were EVERYWHERE I can't even explain it) when I was trying to run a Virtual Machine.

**Comment by hieplpvip** [comment]
Try to boot with argument "-disablegfxfirmware"

You may need to patch ECID. Not sure but you should give it a try

**Comment by AwlsomeAlex** [comment]
I currently don't have macOS Mojave on it, I'm using Ubuntu Budgie 18.10 ATM.
(When my ThinkPad comes in [Past the 30th] I'll try it)
