### ISSUE TITLE
Support UX306UA 

### ISSUE THREAD

**Issue by Autines** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#18]
**What is your laptop?**
Asus UX306UA 
**Full specs**
Screen Size: 13.3 inches
Display: 13.3" Full HD (1920 x 1080) Anti-Glare Display
Graphics Card: Intel HD Graphics 520
Processor: Intel Skylake Core i5-6200U Dual-Core (2.3GHz-2.8GHz）
RAM: 8GB (On Board) LPDDR3 1600MHz
Hard Drive: 512GB SATA SSD
USB: 1 x USB 3.0 port(s)  1 x Type-C
Chip: 100-series
**Attach original DSDT from Clover**

[origin.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2478971/origin.zip)

**Attach full report from AIDA64 (if possible)**

**Comment by wallforfry** [comment]
Hi ! Is UX306UA now supported ?
