### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by Alphonse99** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#24]
**What is your laptop?**
UX410uq
**Which version of macOS are you using?**
Majave
**Describe the problems**
Battery drain 1% per minute
**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**
Can not user gen debug it alway error can not connect internet event not connect via lan or wifi
**Screenshots**

**Additional context**

**Comment by hieplpvip** [comment]
@Alphonse99 I have the same laptop as you. Currently mine can run for about 3-4 hours every charge (not very good but since this is Hackintosh it's acceptable for me).

Because you didn't attach debug files, I can't help you
