### ISSUE TITLE
better check your UX410UQK hotpatch compatibility with latest 309 BIOS

### ISSUE THREAD

**Issue by LeeBinder** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#25]
Greetings @hieplpvip : 

https://www.asus.com/Laptops/ASUS-ZenBook-UX410UQ/HelpDesk_BIOS/

Also (suggestion): indicate in your supported models list after each model: "tested working up to BIOS xyz" :)

👍

**Comment by Alphonse99** [comment]
Do you got prblem with battery drain in this model?

**Comment by LeeBinder** [comment]
@Alphonse99 sorry I don't have this model but Asus Vivobook S15. Just wanted to alert hieplpvip/ baohiep to the latest BIOS 309.

Apart from that, I would not exactly call the Vivobook's general poor battery performance - even in Windows - a full-on "drain". In all sorts of tests and reviews, Asus has been accused of putting too weak batteries into the Vivobook S15 series Laptops. Maybe it's the same with Zenbook.

To narrow down:

1. check in macOS Activity Monitor:
- Energy Tab (the one in the middle)
- View/ All Processes
- sort by Energy Impact, highest on top

See which processes consume the most. If it's apps, uninstall them, reboot

2. Try a different BIOS

3. Boot Windows and work in it for a while to find out if battery performance is as bad in Windows, too

4. For finetuning, if you are not already using the correctly modded CPUFriend kexts, you can run a tool like [freqVectorsEdit.sh](https://github.com/Piker-Alpha/freqVectorsEdit.sh)

**Comment by hieplpvip** [comment]
Running latest BIOS. Everything is good

**Comment by LeeBinder** [comment]
Welcome back, @hieplpvip :) Did you see that Asus updated to BIOS v.311 for your UX410UQK on 2019/06/06?

https://www.asus.com/Laptops/ASUS-ZenBook-UX410UQ/HelpDesk_BIOS/

For all current Vivobook series, all newer BIOS suddenly require RehabMan's VoodooTSCSync (Time Stamp Counter) kext. Does that not apply to your Zenbook UX410UQK? Or have you found a substitute for the kext right in Clover (hotpatch or alike)?

The little issue with the TCS kext is somewhat of a slow-down (a bit worse benchmarks), so we're looking for a way to substitute it with something more efficient.
