### ISSUE TITLE
USB-C doesn't recognize iPad Pro anymore after a second connection on UX430UQ

### ISSUE THREAD

**Issue by lorenzolat** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#26]
**What is your laptop?**
Asus UX430UQ
**Which version of macOS are you using?**
macOS Mojave 10.14.1
**Describe the problems**
I've connected my iPad Pro through Thunderbolt (USB-C) and the Hackintosh recognized it. After a second connection, it's no longer recognized. 
**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**

**Screenshots**

**Additional context**

**Comment by hieplpvip** [comment]
I'm aware of the problem with USB-C. It's due to incorrect patch in SSDT.
Will fix it soon.
