### ISSUE TITLE
Bluetooth sometimes doesn't wake up after sleep

### ISSUE THREAD

**Issue by xseignard** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#30]
**What is your laptop?**

UX430R
**Which version of macOS are you using?**

10.14.2
**Describe the problems**

I sometimes loose bluetooth after sleep

**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**
[debug_13244.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2765473/debug_13244.zip)

**Screenshots**
Not applicable

**Additional context**
Started to happen after update from 10.14.1 to 10.14.2

**Comment by hieplpvip** [comment]
@xseignard I'm aware of this issue. No fix for now :(

**Comment by xseignard** [comment]
Ok, I already had the issue with my UX330 (before it was stolen 😞 )
That's ok for me, I can leave with a reboot from time to time!

**Comment by Vmonheros** [comment]
Use the Bluetooth injector I provided in wifi ticket. If you have a dell 1560, it works everytime !

**Comment by xseignard** [comment]
Yes I have a dell1560 (aka. BCM94352Z) this is the second one I buy from [here](https://www.aliexpress.com/item/Wireless-Adapter-Card-for-Hackintosh-dell-DW1560-BCM94352Z-NGFF-M-2-WiFi-WLAN-Bluetooth-4-0/32862859069.html?spm=a2g0s.9042311.0.0.47e24c4dhKSDGd) and they work well (wifi and BT).

@Vmonheros So I removed `BrcmFirmwareRepo.kext` and `BrcmPatchRAM2.kext` from `/L/E` and put the kext you provided here https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/issues/28#issuecomment-454469371 in `/S/L/E`
Bluetooth is still working, I'll see how it goes over the time and will report here.

(@Vmonheros merci de ton aide et de ta réactivité, ça fait plaisir 👍 bonjour de Nantes!)

**Comment by Vmonheros** [comment]
I'm interested to see you result.

I'd got this BT issue previously, with this injector nether. As it relies on native OS X capabilities, it's certainly the good way for the ones that have Dell 1560.

(@xseignard De rien, faire des Hackintosh c'est partager ! En plus l'injecteur est tout petit. C'est pas plus mal quand on fait de l'injection avec Clover).

**Comment by xseignard** [comment]
Salut @Vmonheros !
So I tried your kext, an put my hackintosh on sleep for the night (closing the lid).
This morning, the bluetooth was still there, but it was impossible to connect back my mouse.
I tried a reboot, and still imossible to connect it back.
I tried to remove the device from the paired ones, and tried a new paring sequence, but the mouse wasn't recognized. I had to remove your kext, and put back `BrcmFirmwareRepo.kext` and `BrcmPatchRAM2.kext` in `/L/E` rebuild the kext cache and reboot to use my mouse again.

So as a conclusion, your method didn't work for me. Dommage!

Thanks again for this lead!

Regards

**Comment by Vmonheros** [comment]
Hi.

I've got another idea. With my last test, I discovered that with AsusSMC, you don't need to  use PTSWAK SSDT change to avoid USB wake. However, I also discovered that I need to use the USB injectors (not "default DSDT", don't ask me why as they contain exactly the same definition)  to not have wake just after sleep when the laptop is wire powered.

At present time, I can wake my laptop with my external usb mice even on wire ;) (bref, pas de wake sur secteur même quand j'ai quelque chose branché en USB, tout celà sur secteur et sans changement du DSDT ;)).

Do you want to test. Perhaps that with this configuration, BT will be OK for you after sleep.

[USBPorts.kext.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2770105/USBPorts.kext.zip)

It is my usb injector. Look inside the plist, it's USB definition. Need nothing more. However, you will have to change your SSDT to avoid WAK modification. And also disable the rename to XWAK in Clover. 

To be honest, it's a pure accidental discovery :p.

**Comment by Rybo713** [comment]
Try going to  on the status bar and clicking sleep instead of just closing the lid. Bluetooth seems to work almost all the time using this method.

**Comment by whatnameisit** [comment]
No USB sleep/wake issues on X510UA-BQ490 at least in 10.15.2.

**Comment by xseignard** [comment]
Yeah, dunno what's the status of this repo, but I fixed the problem using the following kexts:
https://github.com/acidanthera/BrcmPatchRAM
