### ISSUE TITLE
UX430UAR video not working with bios 307

### ISSUE THREAD

**Issue by Vmonheros** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#32]
**What is your laptop?**
UX430UAR

**Which version of macOS are you using?**
OS X 10.14.3

**Describe the problems**
Video card is instable with bios 307. Downgrading to release 305 and everything works.

I tried one week to install OS X with bios 307 without success. When I can install it, video is instable, and acceleration is not really working (even if Hackintool says that acceleration is enable). 

I'm not sure it is ACPI related as I tried also to modify as less as possible (just with some Clover injection, no battery etc...). And same result. I injected many different Platform ID and Device ID as a can. I also look at coffee lake UHD 630 id's. I also go with FakePCIID (and not WhatEvergreen) with same result.

I also tried to enable CMS in bios, with no result.

I didn't check the Video GOP version with 305 and 307, but I think there is a change here.

Did someone has a success with bios 307 on UX430 UAR ?

For the one that want to try, you can easily downgrade the bios with EZ Flash in bios (I did it). It doesn't alert when you want to downgrade ;).

Update: I checked again. Release 305 and 307 have the same GOP 9.0.1066. So the issues is not coming from here. I compared also the DSDT and SSDT of the 2 releases, there is just a small add to LID in release 307 DSDT. Nothing important (3 lines). I tested an inject DSDT without the 3 lines, same issue.

I don't know where the problem is coming from, but is is something that hurts OSX video driver in release 307.

Nobody to test ? As I said, you can easily downgrade the bios version in Bios advanced option, with EZ Flash.

In release 305 and 307, NVRAM unlock is at address 0x527 (I checked). So, go with a setup_var 0x527 0x00 to unlock NVRAM. Surely, with the right USB key with good EFI Shell.

**Comment by gulios** [comment]
Thats right, today i've tried to update UX430UA to BIOS 307
Laptop boots fine but stuck on login screen.
It takes more time to show login screen and after that it doesn't response.
Sometimes i can login but after that it's not possible to use UI.

**Comment by Vmonheros** [comment]
It seems that VoodooTSCSync is needed with last Asus Laptop bios.

I didn't try this solution as reverse to an older version is good enough. But it will certainly the way to go with new Asus Laptop.

P.S.: I didn't discover this solution, I found it on another thread on TonyMac

**Comment by hieplpvip** [comment]
@Vmonheros @gulios It'd be very helpful if one of you can test VoodooTSCSync with latest BIOS.

**Comment by gulios** [comment]
You mean this
https://github.com/RehabMan/VoodooTSCSync
?
If yes i can test it later today.

**Comment by hieplpvip** [comment]
@gulios Yes, that's it

**Comment by gulios** [comment]
ok, with that kext laptop works on 307 BIOS.
Can you add it to your automatic scripts?

**Comment by hieplpvip** [comment]
@gulios Thanks for testing. I'll add it soon.

**Comment by gulios** [comment]
great!

**Comment by bliss95** [comment]
System with 307 and 308 wasn't work.
I took courage from you and I tried. My system (Asus UX430UNR) now works fine.
Bios version is now 308.
hopefully we won't get back before the updates.

**Comment by hieplpvip** [comment]
VoodooTSCSync has been added
