### ISSUE TITLE
Tested on UX330UAK (Kabylake)

### ISSUE THREAD

**Issue by Rybo713** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#33]
Everything works except Siri. It would keep saying "Sorry, could you repeat that again?" 
Also the latest BIOS 312 does not boot into MacOS. I'm using BIOS 311 and everything works well. 

Thank you for your guide!

**Comment by hieplpvip** [comment]
1. As I remember, the audio patch for UX330UAK is incomplete, which could make the mic not working. I'm not an expert on AppleHDA, so you should find someone else to help you.

2. VoodooTSCSync has been added to fix problem with latest BIOS.

Close now!
