### ISSUE TITLE
Fan Control UX410/UX3410

### ISSUE THREAD

**Issue by danielk117** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#35]
Hi,
I installed my Asus UX3410 according to the instructions. I installed it as model UX410 because the devices are actually identical (https://www.ultrabookreview.com/14533-asus-zenbook-ux430-ux410-ux3410/). **Almost everything works fine, your manual is really great.** 👍 

Only the fan control doesn't work. I can't see the current values with HWMonitor, nor can I edit them. 
Is this a general problem (according to #22) or is it possibly due to my device?

**What is your laptop?**
Asus UX410/UX3410

**Which version of macOS are you using?**
10.14.3

**Comment by hieplpvip** [comment]
@danielk117 I have switched to VirtualSMC, so HWMonitor can't not read fan speed anymore. But custom fan control still works!

I can say that this is not a problem.
