### ISSUE TITLE
BIOS 312 UX330UAK

### ISSUE THREAD

**Issue by oesayan** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#36]
BIOS version 312 does not boot into Mac (stuck on loading bar with cursor, verbose boot does not give any  useful info). Downgrading to BIOS 311 resolves the issues, so it is clearly BIOS-related.

**Comment by Vmonheros** [comment]
It seems that VoodooTSCSync is needed with last Asus Laptop bios (same issue with my UX430UAR with bios 307).  

I didn't try this solution as reverse to an older version is good enough. But it will certainly the way to go with new Asus Laptop.

P.S.: I didn't discover this solution, I found it on another thread on TonyMac

**Comment by hieplpvip** [comment]
VoodooTSCSync has been added. Should fix this
