### ISSUE TITLE
Updating to Mojave supported?

### ISSUE THREAD

**Issue by daruuro** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#37]
**What is your laptop?**

ASUS UX330UA-AH55

**Which version of macOS are you using?**

10.13.6 - High Sierra.

**Describe the problems**

So, I initially tried to clean install Mojave, but ran into this error:

`kextd[0], (240s):  'AppleACPICPU'`

and it wouldn't get past the boot (in verbose mode). Eventually I gave up, and installed High Sierra (went extremely smoothly) and it works beautifully right now. I did try to upgrade from High Sierra to Mojave to see if that would work, but I once again ran into the above issue.

What I've tried:

Using FakeSMC instead of VirtualSMC (maybe I'm not using it correctly).

Using SMCHelper64.

I know you've been able to upgrade to Mojave just fine, can you detail to me how to do that?

**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**

Will do, soon.

**Screenshots**

https://i.redd.it/hy5cz5uodto11.jpg

**Comment by hieplpvip** [comment]
Please send me your EFI folder.

**Comment by hieplpvip** [comment]
See [this](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/issues/41).

Perhaps you're using RehabMan's CLOVER version, which is not up to date. Please use official CLOVER version.
