### ISSUE TITLE
macOS Mojave (10.14) - Can't boot into installer (UX330UAR)

### ISSUE THREAD

**Issue by ghost** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#38]
**What is your laptop?**

UX330UAR

**Which version of macOS are you using?**

10.14.5

**Describe the problems**

Installer is not booting with error message below, which I believe is the culprit. There are some other lines but I do not believe they are relevant.

AppleLMUController::getSMCProvider Error: Wait for AppleSMC provider timed out
AppleLMUController::start Error: Could not get SMCProvider

**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**

N/A ?

**Screenshots**

N/A

**Additional context**

I've read that the issue could be limited to 10.14.4 and higher, and installing 10.14.3 might work. I will be checking asap. <--- That did not change anything.

**Comment by hieplpvip** [comment]
Send me your CLOVER folder

**Comment by ghost** [comment]
There you go 

[CLOVER.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/3280644/CLOVER.zip)

Also here the last stuff happening on the verbose. 

![20190612_112600](https://user-images.githubusercontent.com/1063206/59339683-ec93b700-8d04-11e9-89b0-556b849a4234.jpg)

Note that i added VirtualSmc.efi manually, as it is not in the guide. I tried with and without, no difference.

EDIT : 

After nearly 30 minutes I saw the mouse for a brief instant - and Apple logo. But its stuck there 

![20190612_113841](https://user-images.githubusercontent.com/1063206/59340655-b0615600-8d06-11e9-929b-e0c6b311ff82.jpg)

EDIT 2 : 

I now have the mouse back (I can move it) 35 minutes in the installer, but nothing happening so far

![20190612_114012](https://user-images.githubusercontent.com/1063206/59340799-fd452c80-8d06-11e9-89be-5e2bab116ec2.jpg)

And after a while now, laptop went to sleep. I don't think it will go any further than that.

**Comment by Rybo713** [comment]
Try disabling airportbrcmfixup and bt4lecontiunityfixup kexts and boot using safe mode.

**Comment by ghost** [comment]
Ok, I will try this in some minutes. I tried 10.14.3 and still had the same issue btw.

**Comment by ghost** [comment]
I tried, that did not work. Still the same issue. 

EDIT : Safe Mode causes KP.

**Comment by Rybo713** [comment]
Oh that’s weird. Did you disable the 2 kexts first?

**Comment by ghost** [comment]
I removed them from the kext folder entirely :/

**Comment by ghost** [comment]
Also from my testing High Sierra does not work either. 

EDIT : Tried flashing an older BIOS, that did not work either.

**Comment by ghost** [comment]
Stopped using RehabMan's Clover builds, and I have now booted. I have a different kind of issue but I will close this.
