### ISSUE TITLE
Graphical issues (WindowServer?) - UX300UAR / 10.14.5

### ISSUE THREAD

**Issue by ghost** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#39]
**What is your laptop?**

UX330UAR - KabyLakeR

**Which version of macOS are you using?**

10.14.5

**Describe the problems**

I have multiple graphical issues :

- During the installer the language selection could not be shown, and sometimes during some boots I had the Apple logo on top of the other windows 
- During second part of the installer, the first time it booted did not do anything, the second time it went through but went from 12 minutes remaining (which lasted more like 25) to "less than a minute remaining" which did not go any further. I had to manually reboot and macOS was actually installed at that point. 
- During the first boot up I was greeted with this : 

![20190613_012821](https://user-images.githubusercontent.com/1063206/59417809-372a3780-8dc8-11e9-94fe-f084d8e24212.jpg)

I had to reboot many times to be able to come even close to finish the setup. 

I was then stuck on the term and condition approval : 

![20190613_013050](https://user-images.githubusercontent.com/1063206/59417869-51641580-8dc8-11e9-875b-1873e08cf437.jpg)

However after many reboots and trial I succesfully created an account and was able to login, kinda : 

![20190613_103701](https://user-images.githubusercontent.com/1063206/59417948-75275b80-8dc8-11e9-885b-9ad6e667ad4d.jpg)

So where I am sitting at right now it what seems to be almost fully functional (Wifi, Sound, Brightness control, Keyboard brightness, QE/CI seems to be working from what I could try and even lid sleep/wake) but completely un-usable. 

I am able to trigger some UI restart by pressing "Pause/Break" key on my keyboard from time to time, and also when pressing the screen brightness keys. 

This video shows the Pause/Break key issue : 

https://www.youtube.com/watch?v=WHBYv-g4BR4

Also here is the verbose when that happens, sorry for the poor quality : 

![VideoCapture_20190613-014503](https://user-images.githubusercontent.com/1063206/59418345-2a5a1380-8dc9-11e9-9b27-0350105797ea.jpg)

I can read something in the like of : "WindowServer[somePID] triggered unnest out of range something something"

And this morning this is where I am sitting at, and I can't reproduce the Pause/Break issue : 

![20190613_103701 (1)](https://user-images.githubusercontent.com/1063206/59418481-64c3b080-8dc9-11e9-9f51-abbe0247bb2e.jpg)

**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**

Here is my clover as for obvious reasons I can't be generating the files. 

[CLOVER_2.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/3285049/CLOVER_2.zip)

Any help would be greatly appreciated, thanks in advance.

**Comment by ghost** [comment]
Also trying High Sierra gives me mixed up results. I can only boot in the installer form time to time. (Maybe nVram issue ?) 

And when going to disk util I can't erase my disk. It just does not do anything after clicking to erase it.

**Comment by ghost** [comment]
Whole issue comes from the new bios released a week ago.

Reverted to old version and everything is working so far.

**Comment by gulios** [comment]
@pradoxxx1337 install this 
https://github.com/RehabMan/VoodooTSCSync
and check if it helps on new BIOS.
In my case that was it and now everything works on newest 307 BIOS.

**Comment by ghost** [comment]
I might give it a go after I am done fixing some issues, thanks for that :)
