### ISSUE TITLE
Blur/Ring Gradient issue - UX330UAR 10.14.5

### ISSUE THREAD

**Issue by ghost** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#40]
Hi,

After getting everything setup'd on Mojave on my UX330UAR I noticed some weird graphical glitches. 

Here is how it looks like : 

![Capture](https://user-images.githubusercontent.com/1063206/59756062-4f4afc80-9289-11e9-82fd-91829b3b1fa4.PNG)

I have tried the solution posted here : 
https://www.tonymacx86.com/threads/help-weird-ring-like-blur-and-images-in-mojave.262566/post-1834064

But that did not work. I just realized a new installation of Mojave, after trying on High Sierra. High Sierra does NOT have this issue. Is there any way to fix that ? Doing graphical work is really hard when the gradients etc are not showing properly.

I also attached the current Clover folder I have (I have all kexts in L/E):

[CLOVER.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/3305541/CLOVER.zip)

Thanks !

**Comment by hieplpvip** [comment]
Spoofing Skylake is the only workaround for now. There is no fix, unfortunately
