### ISSUE TITLE
Mojave Installer Issues

### ISSUE THREAD

**Issue by AwlsomeAlex** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#41]
**What is your laptop?**
ASUS ZenBook UX330UAR

**Which version of macOS are you using?**
macOS Mojave 10.14.5 Installer

**Describe the problems**
When using the Mojave Installer, Verbose mode outputs the following warnings:
`Unsupported PCI`
`Wait for AppleSMC provider timed out`
`Could not get SMCProvider`
`displaypolicyd: Service exited with abnormal code: 1`
`kextd stall[0..2], (240s) 'AppleAPICPU'`

[Screen](https://ibb.co/HH5VPYf)

Eventually it booted but without the keyboard and trackpad working. Is that normal?

[EFI using Clover r4701 RehabMan](http://filedropper.com/efi_3)
[EFI using Clover r4658 RehabMan](http://filedropper.com/efi_4)

EDIT:
I'll also note that it takes a good 10-15 minutes just to get the system at the Installer GUI. I'll report if the system is even usable after an install with a USB Mouse and Keyboard. 

EDIT2:
It also gave out errors about VoodooI2C failing to load.

**Comment by Rybo713** [comment]
Update your Clover Bootloader using https://github.com/Dids/clover-builder. The latest Clover bootloader from Rehabman is not up to date.

**Comment by AwlsomeAlex** [comment]
That's exactly it. Thank you @Rybo713
