### ISSUE TITLE
Graphical Screen Issues

### ISSUE THREAD

**Issue by AwlsomeAlex** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#42]
**What is your laptop?**
Asus ZenBook UX330UAR

**Which version of macOS are you using?**
macOS Mojave 10.14.5

**Describe the problems**
Every once in a while the screen will quickly flash black then go back to normal, but once it got so bad that the whole screen started to "panic" and everything became disoriented. After a few seconds it eventually corrected itself, but it sorta looked like [this](https://i25.photobucket.com/albums/c67/laloosh/Trashed%20Computer/IMG_8405.jpg)
.

[Video of the major glitch occurring.
](https://photos.google.com/share/AF1QipPCmcMxlywLZUantp_JWhPOmupbgQq5vyg7ok_DmGl418PHU8AVNRMaIe1CYICeLQ?key=cm1mT1FUd2NkSm9FVURnbEZtR0IwRjZneFF2Ty13)

**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**
[29552.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/3390084/29552.zip)

**EDIT**
It happened again and couldn't be fixed without a reboot. Is this a WhateverGreen Kext issue?

**Comment by AwlsomeAlex** [comment]
It seems to be getting worse. I've read somewhere it could be BIOS, but I also read that the latest one broke macOS completely. I'm running 301. Also it seems to be acting up with certain things open, like Safari and Word, but with VirtualBox full screen it seemed fine. My DVMT is set to 64M. 

It's getting very annoying to run macOS since it's already happened about 4 times. Any work around? Is this something that needs to be brought to Lilu/WhateverGreen developers? I also saw that setting the SMB to iMac18,1 could fix it. Could that work? 

Any workaround/solution would be greatly appreciated.

**Comment by AwlsomeAlex** [comment]
It appears I reported this a while ago and might have forgotten about it.... Sorry,
I booted with argument `-disablegfxfirmware` since it's done by default but still experience the issues.
@hieplpvip You happen to mention something about patching the ECID. How do I do this?

**Comment by AwlsomeAlex** [comment]
I just did a __well needed__ BIOS update to 310 so I hope that fixes something....

Didn't help.

**Comment by AwlsomeAlex** [comment]
@hieplpvip Anything you could think of? I appreciate your work and hope to use it in action but the screen constantly glitching is unbearable.

**Comment by AwlsomeAlex** [comment]
@hieplpvip I patched my EDID as you previously made mention. Hope that helps....

**Comment by amsalud** [comment]
@AwlsomeAlex Does your hdmi port work? Mine stopped working

**Comment by AwlsomeAlex** [comment]
@aaronsalud This is my internal display doing this, and not sure haven't tested HDMI. I'm also experiencing this issue in High Sierra and the laptop can get quite unusable at times, so a fix would be greatly appreciated.

Also @hieplpvip patching the EDID did not help.....

**Comment by AwlsomeAlex** [comment]
Okay so changing the SMBios to an 'iMac18,1' might've been my solution. If I don't find an instance of it happening, I'll close the ticket.

**Comment by AwlsomeAlex** [comment]
So when the SMBIOS is set to default it happens, when I set it to iMac18,1 in Clover Configurator it happens. But when I go into Clover at boot-time and change it to iMac18,1 it doesn't.....

**Comment by AwlsomeAlex** [comment]
Didn't help. :/

**Comment by AwlsomeAlex** [comment]
[24838.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/3465516/24838.zip)

I'm completely lost.

**Comment by AwlsomeAlex** [comment]
Could it have something to do with the Ambient Sensor? I tried pushing it and the screen went full brightness and I haven't been having problems. I'm keeping console open to see if it catches what happens when it glitches in the logs.

**Comment by AwlsomeAlex** [comment]
Possible solution: I didn't have VirtualSMC.efi in my CLOVER/drivers/UEFI directory. Could this be the culprit? @hieplpvip

**Comment by AwlsomeAlex** [comment]
Closing because the solution was adding the EFI file and spoofing a 2048MB GPU.
