### ISSUE TITLE
Bluetooth and keyboard backlight support on 10.15

### ISSUE THREAD

**Issue by Ubsefor** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#43]
Hello there. Maybe it is too early, but I discovered some minor issues after I updated my Mojave UX430UA-R to 10.15 (public beta 2). Earlier keyboard backlight and BT kexts from Mojave install don't seem to work, everything else works perfectly. 

Any ideas how I can solve this? I understand that it is a bit early to create this issue as kext updates may come up and fix those problems, but still, there it is

**Comment by gulios** [comment]
For BT check this
https://www.tonymacx86.com/threads/macos-catalina-public-beta-is-now-available.278359/page-11#post-1977552
@hieplpvip maybe is worth to replace these kexts in installer (all works on Mojave too)

**Comment by Ubsefor** [comment]
> For BT check this
> https://www.tonymacx86.com/threads/macos-catalina-public-beta-is-now-available.278359/page-11#post-1977552
> @hieplpvip maybe is worth to replace these kexts in installer (all works on Mojave too)

Tried your solution and it helped, now BT is working perfectly fine
And what about keyboard backlight? What kext I should take a look at? AsusNBFnKeys ?
