### ISSUE TITLE
how to use your code? I want to get an ux430 efi, but I do not know how to get it? please  tell me skills? thank you very much!!

### ISSUE THREAD

**Issue by zqb-knight** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#52]
**What is your laptop?**

**Which version of macOS are you using?**

**Describe the problems**

**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**

**Screenshots**

**Additional context**

**Comment by HolzMichel** [comment]
Just refer to the wiki, there is a basic instruction.
