### ISSUE TITLE
UX330UAK HDMI not working

### ISSUE THREAD

**Issue by amsalud** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#53]
**What is your laptop?**
UX330UAK

**Which version of macOS are you using?**
MacOs Mojave 10.14.6

**Describe the problems**
The micro HDMI is not working. Monitor has black screen when plugged in.

**Comment by deniro98** [comment]
@aaronsalud  how you solved a problem with HDMI?
