### ISSUE TITLE
Scripts don’t work

### ISSUE THREAD

**Issue by Ubsefor** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#57]
Please remove the Return carriage symbol ( ‘ \r ’ ) from your scripts as they don’t work in mac os, returning me 
`zsh: ./install.sh: bad interpreter: /bin/bash^M: no such file or directory`

**Comment by Ubsefor** [comment]
Im talking about master branch, not catalina one

**Comment by hieplpvip** [comment]
Hi, I have merge catalina branch into master. install.sh works for me.

Can you test again?

**Comment by Ubsefor** [comment]
> Hi, I have merge catalina branch into master. install.sh works for me.
> 
> Can you test again?

Sorry for long reply, the scripts seem to be working for me, updated kexts with them, thank you

**Comment by Ubsefor** [comment]
Hello, tested scripts again, they seem to fail

Current fix:

Use dos2unix app on all scripts in repo, also in src and tools
And rename folders to remove "?" character at the end of them, so acpi can be build

**And be careful around DSDT and SSDT tables, don’t dos2unix them by mistake!**
**This will cause your hackintosh to fail to boot!**

**Comment by Ubsefor** [comment]
It turned out that it was GitHub’s line ending handling that broke the scripts

So for anyone having this issue on MacOS, simply configure git in the following way:
`git config --global core.autocrlf input`

That should do

More about this here: [GitHub Help Page](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings)
