### ISSUE TITLE
UX410 sound problems

### ISSUE THREAD

**Issue by mpilias232** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#59]
Hi, I'm using UX410U and so far everything was working perfectly. After updating to the latest Catalina version (10.15.2) I am experiencing some audio issues. 

The problem:

After restart native audio speaker device disappears. Restarting solves the problem but not every time. If booted with audio device loaded works properly with no issues until next time.

**Comment by fengahan** [comment]
hello ，How did you solve the problem
