### ISSUE TITLE
Support for UX330UAR

### ISSUE THREAD

**Issue by AwlsomeAlex** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#6]
My laptop is ASUS ZenBook UX330UAR

Intel Core i5-8250U
Intel UHD Graphics 620
Audio Codex: Unknown
2x USB 3.0 (Intel)
1x USB C
1x MiniHDMI
1x Card Reader
1x Headphone Jack (WOAH!)
Trackpad (Unknown, but VoodooI2CHID works)
Intel 100 Chipset
Intel Wireless (Ik its not compatible)
[DSDT.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2347196/DSDT.zip)

**Comment by hieplpvip** [comment]
I think your model is similar to UX430. Try installing build for UX430 (KabyLake-R) and report what works

Also KabyLake-R support is not officially out, something may not work. Audio patch is not complete too. That's why it's marked "partially"

**Comment by AwlsomeAlex** [comment]
Some DSDT Patches which worked for the UX330UAK (i5 7th Gen) didn't work for my UX330UAR. Although I got sound to work 100% with VoodooHDA and AppleHDADisabler. But patches like backlit keyboard, Battery Indicator, Power Management and FN keys + Brightness don't work. But hey at the trackpad works.

EDIT: I didn't use this page but [another](https://github.com/Rybo713/UX330UA-macOS) .

**Comment by AwlsomeAlex** [comment]
Okay. So square one. No Brightness Control, 0% always, FN keys not working and Backlight not working. But at least my trackpad works.

**Comment by AwlsomeAlex** [comment]
Alright, progress. Your Backlight fix kext works perfectly. Almost there to a perfect hackintosh. Now the main problem is Battery Percentage (Not having the FN keys isn't going to kill me)

EDIT: Your custom FN Keys Patch did not work unfortunately.

**Comment by AwlsomeAlex** [comment]
@hieplpvip Okay well using your scripts completely screwed over my machine. Was updating the kernel cache and POOF, reboot and now nothing works. Oh well. I'll try a fresh install and if that doesn't work I'll leave it in your hands, because all I want out of this machine is a simple Battery Indicator, thats kinda essential in my mind. 

EDIT: Only thing I can see screwing something up in SSDT was Disabling of DGPU, since my device doesn't have one. But one of these kexts make it explode...... Or maybe the BCRM kexts? I don't know something made it crash.

**Comment by hieplpvip** [comment]
Did you get kernel panic? If no, send me debug files?

**Comment by AwlsomeAlex** [comment]
Okay..... very odd. Booting with verbose mode threw out a lot of ACPI Errors, but it booted. Nothing is working at this point (Trackpad, Brightness, etc.) What files do you need and how do I go towards retrieving them? Also can't you create a SSDT Patch specific for my system if I provide the DSDT?

**Comment by hieplpvip** [comment]
Did you follow the instruction: https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/wiki/Basic-Instruction

**Comment by AwlsomeAlex** [comment]
My Machine is so frankensteined right now it needs a fresh install. I'll follow the guide either later tonight or tomorrow and get back to you.

**Comment by hieplpvip** [comment]
Send me output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)

**Comment by AwlsomeAlex** [comment]
My current situation, with it utilizing your SSDT and another project's config.plist and kexts. (Aka last working instance). I'll do purely yours next.
[debug_12406.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2351032/debug_12406.zip)

**Comment by hieplpvip** [comment]
Based on debug files you sent, you didn't followed the guide at all. It also seems that you don't really understand what you do. Please, follow my guide!

My patched ACPI files and config.plist need to be used together

**Comment by AwlsomeAlex** [comment]
Yeah I gotta follow the guide. I know kexts but DSDT/SSDT is a whole new area for me and a bit of a learning curve for some reason. I’ll follow it and send you the new Debug.

**Comment by hieplpvip** [comment]
You don't need to reinstall macOS . Just run the scripts in the guide

**Comment by AwlsomeAlex** [comment]
I did, that caused my machine to completely trash out. Also I didn't have force HFS+ anyway so that needs to be done regardless.

**Comment by hieplpvip** [comment]
What do you mean "trash out"?

**Comment by AwlsomeAlex** [comment]
The system wouldn't even boot, it would get half way through the loading screen and poof, reboot. It somehow miracle booted running in verbose mode? And I restored what I had previously working. Also might be good to mention when the kexts were being rebuilt in the install script the system crashed.

**Comment by hieplpvip** [comment]
Rebuild kextcache causing crash is really weird. Seem that you have to reinstall macOS

**Comment by AwlsomeAlex** [comment]
I figured, I'm going to rely souly on your guide for this one. Also should the x86platform thing be installed? I have a hunch that mightve contributed. And if I choose not to install to /Library/Extensions will it just install in clover or the /system/ path?

**Comment by hieplpvip** [comment]
X86platformplugininjextor should be installed, as it make cpu run at lower freq when idle.

Always install kexts to clover. Kexts should also be install to /L/E too, although it's not necessary. Kexts shouldn't be installed in /S/L/E anymore, it's obsolete on 10.11+

**Comment by AwlsomeAlex** [comment]
Noted. I'll keep you updated and when its all said and done I'll provide the debug and HOPEFULLY I'll get a battery indicator.

**Comment by AwlsomeAlex** [comment]
Keyboard Backlight? What a bonus! But no trackpad...... And USB Mouse isn't working. I'll go through the installer on the keyboard.
I used your VoodooI2C not the other one.

Everything is kinda in reverse. Battery Indicator works, Backlight Keyboard Works, but no Trackpad nor USB. 

Im at the macOS Utilities screen, how do I get to the terminal with JUST the keyboard?

Doesn't work with vanilla VoodooI2C either. SSDT patching might be on your end at this point because thats the only thing not working, and USB Mouse which is another strange one.

**Comment by hieplpvip** [comment]
Somehow VoodooI2C doesn't work in Installer anymore, I got this problem too.

Strange that USB mouse doesn't work. If trying other ports not work, open `SSDT-UX430-KABYR.aml`, find this [part](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/blob/master/src/hotpatch/include/SSDT-UIAC-UX430-KABYR.dsl#L5-L59) and delete. Note that it will be a little different, just find device named UIAC and delete it

**Comment by AwlsomeAlex** [comment]
I’ve got a funny feeling pre-v2.0 VoodooI2C will work during the installer, however it’s far too unusable to actually used once installed, just a workaround. And I’ll take a look at that SSDT patch tomorrow.

**Comment by hieplpvip** [comment]
VoodooI2C is rewritten completely from v2.0.

Have you completed installation? If yes, what's working?

**Comment by AwlsomeAlex** [comment]
I haven’t looked at it since last night, and will work on it later on today. I’m going to try the VoodooI2C v1.0 JUST IN THE INSTALLER (I know that works from experience) and doing the fix for the SSDT UIAC.

**Comment by AwlsomeAlex** [comment]
USB is still not working, even removing the part of the UIAC.

HOWEVER, using the v1.0.4 of VoodooI2C did give me enough Trackpad Functionality to get to the installer. Installing system with HFS+ now.

**Comment by AwlsomeAlex** [comment]
Stand corrected, USB just doesn't work in the Installer either. :?

**Comment by hieplpvip** [comment]
USB not work at all or it only not work in Installer?

**Comment by AwlsomeAlex** [comment]
It only didn't work in the installer. However Trackpad isn't working at all.

**Comment by AwlsomeAlex** [comment]
Nevermind. Trackpad is working with Alex's VoodooI2C (I switched them out) and when the SSDT patches were installed to the system. Everything works! :) 

I don't know if the UIAC had anything to do with it, but you can use the same files/config from UX430 to UX330UAR. You sir are amazing.

Some other things to point out with be sleep is a little glitchy. And maybe the provided clover_kext should be separated into usb_clover_kext to include the old VoodooI2C (since we both had that problem) and clover_kext  with the new VoodooI2C (which will be installed to the system).

However, I don't know if my battery is incredibly well, the system is running super idle (Leaving it at desktop) or what, but the battery says 100%, I'll let you know if that changes. 

Nevermind battery indicator works (phew).

**Comment by hieplpvip** [comment]
My version of VoodooI2C should work too, can you try it? It has better multitouch gestures
How are USB and audio working?

**Comment by AwlsomeAlex** [comment]
USB is working fine and audio is no problem at all. 
As for your VoodooI2C Drivers, I'll check that out later, because I'm experiencing no issues with multitouch gestures.

**Comment by AwlsomeAlex** [comment]
I mean using your VoodooI2C drivers made it a lot snappier, which I don't particularly like, and there was no middle to my preference, however all of the gestures showed up in the Trackpad Settings so looks like I just have to live with it.... Actually your kext glitched the heck out of clicking on the trackpad, with it not identifying clicks reliably. Along with dragging, which was a little buggy too. Probably going to switch back to the one I was using since I don't use those features anyway.

**Comment by hieplpvip** [comment]
Do you have to delete UIAC?

**Comment by AwlsomeAlex** [comment]
No I used the UX330 (Kaby Lake-R) you provided.

**Comment by hieplpvip** [comment]
Great

**Comment by AwlsomeAlex** [comment]
I don't know why some UX430 (Kaby Lake-R) have audio issues but Ive experienced none of this. If you could point out a scenario where this happened or how to replicate it I could give it a shot. Otherwise this device is **FULLY** supported.

**Comment by hieplpvip** [comment]
Test headphone. It doesn't work on UX430

**Comment by AwlsomeAlex** [comment]
As soon as I get a pair, however I know I used VoodooHDA and AppleHDADisabler and it had an option for both Speakers and Headphones, however it identified headphones as always in and would sometimes default to it. Never tested sound though.

**Comment by hieplpvip** [comment]
Have you tested headphone?

**Comment by AwlsomeAlex** [comment]
Headphones do work (I used speakers but they're essentially the same) however when headphones are plugged in the Internal Speakers do not show up, I'm assuming they're disabled when speakers/headphones are plugged in.

**Comment by hieplpvip** [comment]
It's normal behaviour. So your model is fully supported. Congratulation! :)

**Comment by AwlsomeAlex** [comment]
Thanks, whats the deal with Mojave?

**Comment by hieplpvip** [comment]
I haven't testes, but some report it works well on Mojave

**Comment by AwlsomeAlex** [comment]
When the GM is released (because I know VoodooI2C was reporting issues with Mojave and needed the GM source code to fix) I’ll test it out. Also where did you learn how you SSDT Hotpatch because I want to do the same to my friends ThinkPad T420 and possibly the X240 that I’m thinking about getting.

**Comment by hieplpvip** [comment]
https://www.tonymacx86.com/threads/guide-using-clover-to-hotpatch-acpi.200137/

It's better to use normal static patching to get macOS working and then switch to hotpatch.

P/s: It takes me 1 year to create this repo. If you don't have that much time, you should use static patching
