### ISSUE TITLE
10.15.3

### ISSUE THREAD

**Issue by gulios** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#62]
Hi, 
UX430UA

After latests update to 10.15.3 stopped working:
- keyboard backlight fn +f3/4
- sleep fn + f1/1
- brightness fn + f5/6
only audio fn +f10/11/12 works fine

**Comment by mpilias232** [comment]
Hello,
UX410U
I have exactly the same problem since 10.15.2
It is dual booting and I also noticed that only with Bios v312 same happens with windows installation.

**Comment by gulios** [comment]
ok, pulled again download.sh + install.sh because saw new release of
https://github.com/hieplpvip/AsusSMC/releases/tag/1.2.1
and it works fine now !!!
Thank you @hieplpvip
