### ISSUE TITLE
Advise to use the official recommended method to set up WhatEverGreen and AppleALC

### ISSUE THREAD

**Issue by luvletter2333** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#63]
I can't know how your config.plist setup AppleALC until I saw the AppleALC wiki.
Source:
- `Note: It is necessary to set value layout-id in Devices-Properties or boot arguments.`
in https://github.com/acidanthera/AppleALC/wiki/Installation-and-usage

**Comment by hieplpvip** [comment]
Fixed now.
