### ISSUE TITLE
No audio - UX430UA

### ISSUE THREAD

**Issue by mynameisvasco** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#7]
**What is your laptop?**
UX430UA
**Which version of macOS are you using?**
Mojave 10.14
**Describe the problems**
I have no audio.
**Additional context**
i5-7200U is my processor.

**Comment by hieplpvip** [comment]
The new patch for UX430 is included in new AppleALC. However, it hasn't been released yet. You need to compile it manually
https://github.com/acidanthera/AppleALC
Use layout-id 14

**Comment by hieplpvip** [comment]
[1.3.1 (RELEASE).zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2353254/1.3.1.RELEASE.zip)
Install this kext, use layout-id 14 (0x0E)

**Comment by mynameisvasco** [comment]
Still not working.

**Comment by hieplpvip** [comment]
Send me output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)

**Comment by mynameisvasco** [comment]
[debug_9039.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2356572/debug_9039.zip)
Here it is 👍

**Comment by hieplpvip** [comment]
Did you replace AppleALC in /Library/Extensions?

**Comment by mynameisvasco** [comment]
Isn't it in kext folder?

**Comment by hieplpvip** [comment]
You have installed AppleALC in two places: CLOVER/kexts/Others and /Library/Extensions. Seems that you have replaced kext in CLOVER but forgot /L/E. To do it, open Terminal:
```
cd <where_you_downloaded_applealc>
sudo rm -Rf /Library/Extensions/AppleALC.kext
sudo cp -R AppleALC.kext /Library/Extensions
sudo kextcache -i /
```

**Comment by mynameisvasco** [comment]
Now it detects the laptop speakers and it allows me to change volume etc. But still no audio when I play anything.

**Comment by mynameisvasco** [comment]
But if I connect headphones using jack i get sound in headphones

**Comment by hieplpvip** [comment]
Does speaker work after disconnecting headphone?

**Comment by mynameisvasco** [comment]
No. Only headphones work.

**Comment by hieplpvip** [comment]
Can you dump your codec?
Instruction here: http://osxarena.com/2015/09/getting-codec-information-for-applehda-patching/

**Comment by mynameisvasco** [comment]
cat: /proc/asound/card0/codec#0: No such file or directory
cat: /proc/asound/card0/codec#1: No such file or directory

**Comment by hieplpvip** [comment]
That's really strange

**Comment by mynameisvasco** [comment]
Yes it is.

**Comment by gulios** [comment]
are you sure, you have ALC295?
Install this https://sourceforge.net/projects/dpcimanager/ and show what you have in "Codec ID".
It's same model as mine but different CPU, so maybe audio is different too.

**Comment by mynameisvasco** [comment]
![image](https://user-images.githubusercontent.com/31479521/45589930-2ececa00-b926-11e8-8613-1653b7194285.png)
Here it is.
