### ISSUE TITLE
Darkwake/powernap issues

### ISSUE THREAD

**Issue by Ubsefor** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#76]
After waking my hackintosh after it went to «deep sleep» a.k.a standby mode and having a darkwake, the igpu freaks out and caps at 0.75 GHz minimum, resulting in terrible performance. I suspect that Lilu/Whatevergreen are responsible for this, as I compiled the kexts manually from the latest commits, and before that this problem left me with igpu capped only at 0.3 GHz, which was acceptable. I’ll attach a screenshot to describe the problem
![2020-07-25_10 42 12](https://user-images.githubusercontent.com/38097265/88487440-c8894880-cf8d-11ea-900b-e805f2f7de10.png)

**Comment by Ubsefor** [comment]
I did manually patch DSDT so it doesn’t give compilation warnings with values not returning: 
[SSDT-UX430-KabyLakeR.aml.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/4981839/SSDT-UX430-KabyLakeR.aml.zip)
Will be testing some other options further
If anyone has properly working powernap/darkwake, could you please upload your config (boot section, mainly – darkwake boot argument) and pmset values (pmset -g in Terminal)

**Comment by bliss95** [comment]
Have you tried the latest whatever kext.

I have encountered similar CPU / GPU slowdown issues recently after sleep. Recent kexts have solved these problems.

**Comment by Ubsefor** [comment]
> Have you tried the latest whatever kext.
> 
> I have encountered similar CPU / GPU slowdown issues recently after sleep. Recent kexts have solved these problems.

Idk what the problem is, the reason is that I get similar behavior when I use kexts, which I compile from sources

Every release version does not have such problem

**Comment by Ubsefor** [comment]
According to vit9696, Apple broke the Intel GPU drivers recently, so I will close this issue as it won’t fix :(
