### ISSUE TITLE
How create opencore version?

### ISSUE THREAD

**Issue by piyuyi** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#81]
Hi. Can someone tell me how create the EFI folder for opencore?
If I follow the basic instructions, it just can create the EFI for clover version.

Thank you.

**Comment by hieplpvip** [comment]
Hi, `opencore` branch has been merged into `master`. I will add instruction for it in a few days. Please wait.

**Comment by piyuyi** [comment]
OK, thank you!
