### ISSUE TITLE
FN-Buttons for sleep and airplane mode not working on Big Sur on UX430UA-R

### ISSUE THREAD

**Issue by Ubsefor** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#82]
After applying patches for DSDT for enabling FN-Buttons (F1 for sleep, F2 for airplane mode), I noticed, that on Big Sur these buttons don’t work. As a solution for sleep – I can just tap power button, but Airplane Mode can’t be toggled.

**Comment by teekiai** [comment]
Hi Ubsefor,

Can you help me to make Big Sur to install? What guide you have used? I used few guides to install and have failed.
My Laptop is same as yours (I think). UX430UA-R i7-8550U/UHD620/8Gb/1TB
Mayby i can use yours EFI to make my own from yours copy?

**Comment by Ubsefor** [comment]
> Hi Ubsefor,
> 
> Can you help me to make Big Sur to install? What guide you have used? I used few guides to install and have failed.
> My Laptop is same as yours (I think). UX430UA-R i7-8550U/UHD620/8Gb/1TB
> Mayby i can use yours EFI to make my own from yours copy?

Use OC-branch of this repo, there are DSDT patches, read OC install guide for your platform

**Comment by piyuyi** [comment]
+1, can you share your OC efi folder with us, please?

**Comment by Ubsefor** [comment]
Issue is fixed, needed to install the newest daemon
