### ISSUE TITLE
Drivers weren't installed UX430UN

### ISSUE THREAD

**Issue by aliaksandr-chaulytka** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#86]
**What is your laptop?**
Asus ZenBook 14 UX430UN-GV131T

**Which version of macOS are you using?**
Catalina 10.15.6E 

**Describe the problems**
I did steps following `Basic Instruction`
Logs were success but I didn't see the differences.
Drivers weren't installed =(

**Comment by hieplpvip** [comment]
Hi, the documentation in Wiki is for Clover. I will update doc for OpenCore soon.

**Comment by aliaksandr-chaulytka** [comment]
> Hi, the documentation in Wiki is for Clover. I will update doc for OpenCore soon.

I copied files from `build` to EFI.
![photo_2020-10-12_00-09-23](https://user-images.githubusercontent.com/20597176/95690322-859b5080-0c1f-11eb-9ef2-b7ffc4a542f3.jpg)

I can't load os.
I return to this screen again and again after tap option '1'  =(

**Comment by aliaksandr-chaulytka** [comment]
I have followed the new instruction and all is working. 
@hieplpvip Great job. You are awesome!
