### ISSUE TITLE
Possible Support for Asus x509FA - Need Help

### ISSUE THREAD

**Issue by ianmubangizi** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#89]
Hey, @hieplpvip 

Thanks for you work on the Asus laptop support, I was trying out your AsusSMC, I noticed the key you have in your patches are totally different to my laptop hotkeys, I just wanted to know how may I map you AsusSMC code to match mine.

Also, I made a repo of my running config here for the [Asus x509FA](https://github.com/ianmubangizi/oc.macos.asus-x509)

**Comment by ianmubangizi** [comment]
I managed to get it working, I had put the AsusSMC before VirtualSMC

Hotkeys work great, looking forward to a solution for _Q0C (Keyboard Backlight Down) never getting called.
`Method (_Q0C, 0, NotSerialized)  // _Qxx: EC Query
 {
     KBLD ()
 }
`

**Comment by hieplpvip** [comment]
Your laptop has only one key for keyboard backlight, right?

**Comment by ianmubangizi** [comment]
Yes it is the F7 key
