### ISSUE TITLE
Support UX331UA

### ISSUE THREAD

**Issue by CrAazZyMaN21** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#9]
**What is your laptop?**

ASUS Zenbook 13 UX331UA (90NB0GZ1-M00370)

**Full specs**

Display | 13.3", 1920x1080, 166dpi, non-glare, IPS, Digitizer
Intel Core i5-8250U, 4x 1.60GHz
8GB DDR3L
256GB M.2 SATA (2280) or 512GB M.2 NVME (2280)
Intel UHD Graphics 620 (IGP), HDMI 1.4
1x USB-C 3.0, 2x USB-A 3.0
Intel(R) Dual Band Wireless-AC 8265 
Bluetooth 4.2
Li-Polymer, 50Wh, 14h Runtime
1.12kg
illuminated keyboard, Fingerprint-Reader

Source: https://geizhals.at/asus-zenbook-13-ux331ua-blau-90nb0gz1-m00370-a1721812.html

**Attach original DSDT from Clover**

https://puu.sh/BAnlv/1d3424e77a.aml

**Attach full report from AIDA64 (if possible)**

https://puu.sh/BApap/34e457dc4e.txt

**Comment by AwlsomeAlex** [comment]
@CrAazZyMaN21 I would say try installing it with the UX330UA (Kaby Lake-R) config and SSDT and reporting back here how that works out. I wouldn't do Mojave at the moment though, trackpad is bound to not work, so stick with High Sierra. You might need a mouse handy for the installation part.

**Comment by CrAazZyMaN21** [comment]
@AwlsomeAlex Hi, I used the Script and some things aren't working.

**Working:** 

- FN Keys
- Voodoo PS2 and Voodoo I2C
- USB Inject
- NullEthernet
- FakeSMC
- FakePCIID
- Bluetooth

**Not Working:**

- Clover Boot Entry (Fixed with manual entry on Windows with EasyUefi)
- iGPU Graphics (Devices - IntelGFX: 0x59168086 | Graphics - ig-platform-id: 0x59160000 and Inject Intel | Patched it myself, not working with the script)
- Battery (RehabMan Laptop-DSDT-Patch - battery_ASUS-N55SL.txt | Just showing 0% | Patched it myself, not working with the script)
- Audio (RehabMan VoodooHDA | Patched it myself, not working with the script)
- Backlight and Keyboard Light can't be changed (Haven't found a fix yet)
- Intel WLAN (obviously not working)
- HW Monitor (Doesn't start at all and skip installation of it)

**Comment by AwlsomeAlex** [comment]
Hmmm.... If you could please post the .zip [generated by this](https://github.com/black-dragon74/OSX-Debug) for @hieplpvip to debug. Along with the patched DSDT and the patches used for the DSDT.

Also it is safe to install with Mojave now. (Hopefully!)

Also the repository was recently updated to replace FakeSMC with AsusSMC (gives specific ASUS support), did you try it with this?

**Comment by hieplpvip** [comment]
@CrAazZyMaN21 Sorry, but I'm spending time solving issue with VoodooI2C, so you have to wait 

@AwlsomeAlex FakeSMC is replaced with VirtualSMC. AsusSMC is a plugin of VirtualSMC
