### ISSUE TITLE
UX310 skips OpenCore

### ISSUE THREAD

**Issue by vitorrj** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#94]
UX310UQ, macOS BigSur

I have always used the **Clover** method but with the OpenCore, is not working anymore. I followed all the steps, however when I boot the USB the laptop seems to **skip the bootloader**, restart and follow my next boot option. As if 'was not there'
I have the following the structure
- ESP 
   - EFI
       - BOOT
       - OC

I downloaded the `debug` version of OpenCore and that's what has been showing to me
![IMG_0279](https://user-images.githubusercontent.com/52195896/99085451-7dd91e00-25c8-11eb-91e8-c377c8ed8ec5.jpeg)

**Comment by jessjosephbenny** [comment]
I am also facing this issue. Have you found any solutions?

**Comment by vitorrj** [comment]
I don’t know if it’s related but after I deleted the commented lines in smbios.txt started working. The problem I am having now is that I am not being able to download BigSur, it always fails to download

**Comment by shootlazer** [comment]
Same here on an UX410 and also coming from a previous Clover installation. And when it automatically attempts to boot Windows (which is on a separate SSD), it BSODs.

Fun fact, OpenCore USB will boot my installed OpenCore partition. But it won't boot without the USB.

What fixed it for me is doing what this post said.
https://github.com/hieplpvip/Asus-Zenbook-Hackintosh/issues/87#issuecomment-709664025

**Comment by finax1** [comment]
The generated config.plist disables the picker and sets the picker-timeout to 0... 
@hieplpvip Since many users dual-boot windows, it makes more sense to enable the picker👍🏻

**Comment by vitorrj** [comment]
@shootlazer Indeed that was the problem! Thanks

 @hieplpvip I agree with @finax1, it might be less confusing/easier to debug if the picker is enable

Anyway, done!
![UX310 updated to Big Sur](https://user-images.githubusercontent.com/52195896/99370386-e7557700-28bd-11eb-8c94-6ec2774f8c5c.png)

**Comment by finax1** [comment]
@vitorrj Which SMBios did u use? I use MacBookPro14,1 and therefor I had to disable SecureBootModel. 

@hieplpvip What is your experience, which is the best SMBIOS for UX430UN KabyLake-R ?

**Comment by vitorrj** [comment]
@finax1 Me too, MacBookPro14,1! Mine `SecureBootModel` is set to `default` and so far is booting normally 🤗

**Comment by VGerris** [comment]
this issue is not fixed yet, ShowPicker true + timeout works.
The linked PR does not seem to have an update, would be great  to have it because it simply does not work without.
My problem in UX310UAK is that I just get a grey sceen in the bigsur installer, I will research and create a ticket for that if I can't solve it.
